apiVersion: v1
kind: Service
metadata:
  name: service
spec:
  selector:
    app: ligne-rouge
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
    - protocol: TCP
      port: 3306
      targetPort: 3306
  type: LoadBalancer
